<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <Compile Update="World.Operations.cs">
        <DependentUpon>World.cs</DependentUpon>
      </Compile>
      <Compile Update="World.Actors.cs">
        <DependentUpon>World.cs</DependentUpon>
      </Compile>
      <Compile Update="World.Handlers.cs">
        <DependentUpon>World.cs</DependentUpon>
      </Compile>
      <Compile Update="World.Errors.cs">
        <DependentUpon>World.cs</DependentUpon>
      </Compile>
      <Compile Update="World.Components.cs">
        <DependentUpon>World.cs</DependentUpon>
      </Compile>
      <Compile Update="World.Entry.cs">
        <DependentUpon>World.cs</DependentUpon>
      </Compile>
      <Compile Update="World.ComponentPools.cs">
        <DependentUpon>World.cs</DependentUpon>
      </Compile>
      <Compile Update="Components\ComponentPool.Errors.cs">
        <DependentUpon>ComponentPool.cs</DependentUpon>
      </Compile>
      <Compile Update="Components\ComponentPool.Handlers.cs">
        <DependentUpon>ComponentPool.cs</DependentUpon>
      </Compile>
      <Compile Update="Components\ComponentPool.Operations.cs">
        <DependentUpon>ComponentPool.cs</DependentUpon>
      </Compile>
      <Compile Update="Filters\Filter2.Errors.cs">
        <DependentUpon>Filter2.cs</DependentUpon>
      </Compile>
      <Compile Update="Filters\Filter2.Handlers.cs">
        <DependentUpon>Filter2.cs</DependentUpon>
      </Compile>
      <Compile Update="Filters\Filter2.Listeners.cs">
        <DependentUpon>Filter2.cs</DependentUpon>
      </Compile>
      <Compile Update="World.Events.cs">
        <DependentUpon>World.cs</DependentUpon>
      </Compile>
      <Compile Update="Components\ComponentPool.Producer.cs">
        <DependentUpon>ComponentPool.cs</DependentUpon>
      </Compile>
      <Compile Update="Components\ComponentPool.Subscriptions.cs">
        <DependentUpon>ComponentPool.cs</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
