<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <Compile Update="Components\ComponentPool.Errors.cs">
        <DependentUpon>ComponentPool.cs</DependentUpon>
      </Compile>
      <Compile Update="Components\ComponentPool.Handlers.cs">
        <DependentUpon>ComponentPool.cs</DependentUpon>
      </Compile>
      <Compile Update="Components\ComponentPool.Operations.cs">
        <DependentUpon>ComponentPool.cs</DependentUpon>
      </Compile>
      <Compile Update="Filters\Filter2.Errors.cs">
        <DependentUpon>Filter2.cs</DependentUpon>
      </Compile>
      <Compile Update="Filters\Filter2.Consumers.cs">
        <DependentUpon>Filter2.cs</DependentUpon>
      </Compile>
      <Compile Update="Components\ComponentPool.Producers.cs">
        <DependentUpon>ComponentPool.cs</DependentUpon>
      </Compile>
      <Compile Update="Filters\Filter2.Handlers.cs">
        <DependentUpon>Filter2.cs</DependentUpon>
      </Compile>
      <Compile Update="Worlds\World.Producers.cs">
        <DependentUpon>World.cs</DependentUpon>
      </Compile>
      <Compile Update="Worlds\World.Consumers.cs">
        <DependentUpon>World.cs</DependentUpon>
      </Compile>
      <Compile Update="Worlds\World.Filters.cs">
        <DependentUpon>World.cs</DependentUpon>
      </Compile>
      <Compile Update="Worlds\World.Actors.cs">
        <DependentUpon>World.cs</DependentUpon>
      </Compile>
      <Compile Update="Worlds\World.ComponentPools.cs">
        <DependentUpon>World.cs</DependentUpon>
      </Compile>
      <Compile Update="Worlds\World.Components.cs">
        <DependentUpon>World.cs</DependentUpon>
      </Compile>
      <Compile Update="Worlds\World.Entry.cs">
        <DependentUpon>World.cs</DependentUpon>
      </Compile>
      <Compile Update="Worlds\World.Errors.cs">
        <DependentUpon>World.cs</DependentUpon>
      </Compile>
      <Compile Update="Worlds\World.Handlers.cs">
        <DependentUpon>World.cs</DependentUpon>
      </Compile>
      <Compile Update="Worlds\World.Operations.cs">
        <DependentUpon>World.cs</DependentUpon>
      </Compile>
      <Compile Update="Components\ComponentPool.Consumers.cs">
        <DependentUpon>ComponentPool.cs</DependentUpon>
      </Compile>
      <Compile Update="Filters\Filter2.Enumerator.cs">
        <DependentUpon>Filter2.cs</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
